services:
   db:
      image: mongo:latest
      container_name: scrapydbmongo
      ports:
         - 27017:27017
      environment:
         - MONGO_INITDB_DATABASE=scrapydb
         - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb-user
         - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb-pass
      secrets:
         - mongodb-user
         - mongodb-pass
      volumes:
         - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
         - ./scrapydb-data:/data/db
   neo4j:
      container_name: neo4j
      image: neo4j:latest
      ports:
         - 7474:7474
         - 7687:7687
      environment:
         - NEO4J_apoc_export_file_enabled=true
         - NEO4J_apoc_import_file_enabled=true
         - NEO4J_apoc_import_file_use__neo4j__config=true
         - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      volumes:
         - ./neo4j_db/data:/data
         - ./neo4j_db/logs:/logs
         - ./neo4j_db/import:/var/lib/neo4j/import
         - ./neo4j_db/plugins:/plugins
secrets:
   mongodb-user:
      file: ./.secrets/mongodb_user.txt
   mongodb-pass:
      file: ./.secrets/mongodb_pwd.txt